"""Additional quiz questions for the six original CyberAware modules.

Each list contains 20 NEW 7-tuple questions that extend the existing
10-question quizzes in seed.py to a total of 30 per module. Tuple format:
    (question, option_a, option_b, option_c, option_d, correct_letter, explanation)
correct_letter is one of A, B, C, D and varies across each list.
"""

SECURE_CODING_EXTRA = [
    (
        'Which input-validation strategy is generally the most secure?',
        'Allowlisting only known-good input',
        'Blocklisting known-bad characters',
        'Truncating long input',
        'Lowercasing all input',
        'A',
        'Allowlisting accepts only values that match an expected format, which is far harder to bypass than trying to enumerate every bad pattern.',
    ),
    (
        'A stack buffer overflow is most directly enabled by:',
        'Using bounds-checked APIs',
        'Writing more data than a fixed buffer can hold',
        'Encrypting the heap',
        'Validating input length',
        'B',
        'Writing past a fixed-size buffer overwrites adjacent memory such as the return address, which an attacker can exploit.',
    ),
    (
        'Output encoding should be chosen based on:',
        'The database vendor',
        "The user's locale",
        'The context where data is rendered (HTML, JS, URL)',
        'The server CPU',
        'C',
        'An attacker payload safe in one context can be dangerous in another, so encoding must match the exact output context.',
    ),
    (
        'Which header helps mitigate XSS by restricting allowed script sources?',
        'Accept-Language',
        'Cache-Control',
        'ETag',
        'Content-Security-Policy',
        'D',
        'A Content-Security-Policy lets you whitelist trusted sources and block inline or third-party scripts, reducing XSS impact.',
    ),
    (
        'Storing passwords securely requires:',
        'A slow salted hash like bcrypt or Argon2',
        'Reversible encryption',
        'Base64 encoding',
        'Plain text for recovery',
        'A',
        'Salted, computationally expensive hashes resist cracking; passwords should never be stored reversibly or as fast/un-salted hashes.',
    ),
    (
        'A second-order SQL injection occurs when:',
        'Input is rejected immediately',
        'Stored input is later used unsafely in a query',
        'The database is offline',
        'TLS is disabled',
        'B',
        'Data that looks safe on storage can become an injection payload when it is later concatenated into a query without parameterization.',
    ),
    (
        'The safest way to handle file uploads is to:',
        'Trust the client-provided file name and type',
        'Execute the file to inspect it',
        'Validate type/size server-side and store outside the web root',
        'Allow any extension',
        'C',
        'Server-side validation plus storing uploads outside executable paths prevents attackers from running uploaded code.',
    ),
    (
        'Why should error messages avoid stack traces in production?',
        'They slow the page',
        'They use too much disk',
        'They break caching',
        'They can leak internal paths, queries, and versions',
        'D',
        'Verbose errors disclose implementation details that help attackers craft targeted exploits; show generic messages and log details server-side.',
    ),
    (
        'Dependency (software composition) scanning helps you find:',
        'Known vulnerable third-party libraries',
        'Slow functions',
        'Unused CSS',
        'Spelling mistakes',
        'A',
        'Most apps inherit risk from open-source dependencies; scanners flag versions with published CVEs so you can patch them.',
    ),
    (
        'DOM-based XSS differs from reflected XSS because the payload:',
        'Never reaches the browser',
        'Is processed entirely by client-side JavaScript',
        'Only affects the database',
        'Requires server-side templates',
        'B',
        'In DOM-based XSS the vulnerability is in client-side code that writes untrusted data into the DOM, without the server reflecting it.',
    ),
    (
        'Integer overflow in size calculations is dangerous because it can lead to:',
        'Faster math',
        'Better compression',
        'Undersized buffer allocations and memory corruption',
        'Stronger encryption',
        'C',
        'When a size calculation wraps around, code may allocate too little memory and then write past it, causing corruption or overflows.',
    ),
    (
        'The principle of least privilege applied to a database account means:',
        'Granting it admin rights',
        'Sharing one root account',
        'Disabling all logging',
        'Granting only the permissions the app needs',
        'D',
        'If the app account can only do what it needs, a successful injection or compromise causes far less damage.',
    ),
    (
        'Which is the best practice for managing secrets across environments?',
        'Use a secrets manager with rotation',
        'Commit a .env file with real keys',
        'Hard-code per-environment values',
        'Print secrets to logs for debugging',
        'A',
        'A dedicated secrets manager centralizes access control, auditing, and automatic rotation, keeping secrets out of code and logs.',
    ),
    (
        'Cross-site scripting can be reduced in React/Angular because they:',
        'Disable JavaScript',
        'Escape interpolated values by default',
        'Block all user input',
        'Encrypt the DOM',
        'B',
        'Modern frameworks escape bound values automatically; danger returns when you use raw HTML injection APIs like dangerouslySetInnerHTML.',
    ),
    (
        'A code review focused on security should especially scrutinize:',
        'Variable naming style',
        'Comment density',
        'Trust boundaries and untrusted input handling',
        'Indentation',
        'C',
        'Most vulnerabilities live where untrusted data enters or crosses a privilege boundary, so reviews should focus there.',
    ),
    (
        'Using prepared statements with bound parameters protects against injection by:',
        'Compressing the query',
        'Caching results',
        'Encrypting the connection',
        'Sending data separately from the SQL command text',
        'D',
        "The database receives the query structure and the data independently, so user input can never change the command's meaning.",
    ),
    (
        'Threat modeling during the SDLC is most valuable when performed:',
        'Iteratively, starting at design',
        'After deployment only',
        "Once in the product's lifetime",
        'Only after an incident',
        'A',
        'Identifying threats early and revisiting them as the design evolves catches issues when they are cheapest to fix.',
    ),
    (
        'Which practice best reduces the risk of using outdated, vulnerable components?',
        'Pinning to one ancient version forever',
        'Regular patching and update cadence',
        'Avoiding all libraries',
        'Disabling version checks',
        'B',
        'Keeping dependencies current with a disciplined patch process closes known vulnerabilities before attackers exploit them.',
    ),
    (
        'Server-Side Request Forgery (SSRF) is best mitigated by:',
        'Allowing all outbound URLs',
        'Caching responses',
        'Validating/allowlisting destination hosts',
        'Disabling HTTPS',
        'C',
        'Restricting which hosts the server may call (and blocking internal ranges) stops attackers from pivoting through the server to internal systems.',
    ),
    (
        'Why is client-side validation alone insufficient for security?',
        'It is too slow',
        'It uses too much bandwidth',
        'Browsers disable it',
        'Attackers can bypass the client and call the API directly',
        'D',
        'Client checks improve UX but can be skipped; the server must always re-validate because it is the real trust boundary.',
    ),
]

SOCIAL_ENGINEERING_EXTRA = [
    (
        'Spear phishing differs from ordinary phishing because it is:',
        'Highly targeted and personalized to the victim',
        'Sent to millions randomly',
        'Always harmless',
        'Only sent by SMS',
        'A',
        'Spear phishing uses research about a specific person or role to craft a more convincing, tailored lure.',
    ),
    (
        'Whaling attacks specifically target:',
        'New interns',
        'Senior executives and high-value individuals',
        'Random customers',
        'Printers',
        'B',
        'Whaling aims at executives whose access or authority makes a successful compromise especially damaging.',
    ),
    (
        'Vishing is social engineering conducted via:',
        'Vending machines',
        'Video games',
        'Voice phone calls',
        'VPN tunnels',
        'C',
        'Vishing (voice phishing) uses phone calls, often spoofing caller ID, to pressure victims into revealing data or taking action.',
    ),
    (
        'Quid pro quo attacks lure victims by:',
        'Threatening legal action',
        'Encrypting files',
        'Flooding the network',
        'Offering a benefit or service in exchange for info',
        'D',
        'Quid pro quo dangles something desirable (like free tech support) to coax the target into handing over access or credentials.',
    ),
    (
        "A look-alike domain such as 'micros0ft-support.com' is a sign of:",
        'Typosquatting / domain spoofing',
        'A trusted vendor',
        'A secure site',
        'An internal server',
        'A',
        'Attackers register confusingly similar domains so a quick glance misleads the victim into trusting a malicious site.',
    ),
    (
        'The best response to an unexpected MFA push you did not request is:',
        'Approve it to clear the prompt',
        'Deny it and report the attempt',
        'Ignore it',
        'Approve after a few tries',
        'B',
        'An unrequested prompt likely means someone has your password; deny it and alert security so the account can be protected.',
    ),
    (
        'Business Email Compromise (BEC) typically tries to make you:',
        'Reset your screensaver',
        'Upgrade your laptop',
        'Send money or sensitive data to the attacker',
        'Clean your inbox',
        'C',
        'BEC impersonates an executive, vendor, or partner to trick staff into wiring funds or sharing confidential information.',
    ),
    (
        "Why do attackers spoof a sender's display name?",
        'To improve deliverability',
        'To encrypt the email',
        'To add a signature',
        'Because the display name is easy to fake and trusted',
        'D',
        'Many clients show only the friendly display name; faking it makes a message look like it came from a known person.',
    ),
    (
        'A pop-up claiming your PC is infected and giving a support number is:',
        'Scareware / tech-support scam',
        'A helpful alert',
        'A Windows update',
        'An antivirus license',
        'A',
        'Scareware uses fake alarms and urgency to push victims into calling fake support or installing malware.',
    ),
    (
        'Pharming redirects victims to a fake site by:',
        'Sending a text',
        'Poisoning DNS or hosts file entries',
        'Calling them',
        'Mailing a letter',
        'B',
        'Pharming tampers with name resolution so even a correctly typed URL leads to an attacker-controlled site.',
    ),
    (
        'The most reliable protection against credential phishing is:',
        'Memorizing one strong password',
        'Changing passwords weekly',
        'Phishing-resistant MFA such as FIDO2 keys',
        'Using shorter URLs',
        'C',
        'Hardware-backed FIDO2/WebAuthn keys are bound to the real site origin, so they do not work on phishing pages.',
    ),
    (
        "An email from a 'vendor' suddenly changes their bank account details. You should:",
        'Update the records and pay',
        'Reply asking for confirmation',
        'Ignore the change',
        'Verify by calling a known, trusted number',
        'D',
        'Bank-detail changes are a top BEC tactic; always confirm out-of-band using a previously known contact, not details from the email.',
    ),
    (
        'Shoulder surfing is best prevented by:',
        'Using privacy screens and shielding entry of credentials',
        'Talking louder',
        'Larger fonts',
        'Disabling the firewall',
        'A',
        'Shoulder surfing is observing screens or keystrokes; privacy filters and awareness of your surroundings reduce the risk.',
    ),
    (
        'Dumpster diving is a social-engineering reconnaissance technique that involves:',
        'Hacking the cloud',
        'Searching discarded documents and media for useful data',
        'Spoofing email',
        'Flooding a network',
        'B',
        'Attackers recover sensitive information from improperly disposed paper and devices, so shredding and secure disposal matter.',
    ),
    (
        'Why is urgency such a common element in social-engineering messages?',
        'It is required by email standards',
        'It improves grammar',
        'It pressures victims to act before thinking',
        'It bypasses spam filters',
        'C',
        'Manufactured time pressure short-circuits careful judgment, which is exactly what the attacker wants.',
    ),
    (
        'A watering-hole attack compromises:',
        "The victim's home router",
        'A random ad network',
        "The victim's phone battery",
        'A legitimate site the target group frequently visits',
        'D',
        'Attackers infect a trusted website that their intended victims commonly use, so the targets get compromised by simply browsing normally.',
    ),
    (
        'Angler phishing refers to attacks carried out via:',
        'Fake customer-support accounts on social media',
        'Fishing forums',
        'Postal mail',
        'Fax machines',
        'A',
        'Attackers pose as brand support on social platforms to intercept customers seeking help and steal their details.',
    ),
    (
        'If you accidentally click a phishing link, the best first step is to:',
        'Keep using the account normally',
        'Disconnect, report it, and change affected passwords',
        'Delete the email and forget it',
        'Forward it to colleagues',
        'B',
        'Prompt reporting and credential changes let security contain the incident before attackers can use any captured data.',
    ),
    (
        'Reverse social engineering works by:',
        'The attacker reporting the victim',
        "Encrypting the victim's files",
        'Making the victim seek out the attacker for help',
        'Sending mass spam',
        'C',
        'The attacker first creates a problem or appears as a helpful expert so the victim initiates contact, lowering their suspicion.',
    ),
    (
        'A strong organizational defense against social engineering is:',
        'Removing all email',
        'Letting anyone approve payments',
        'Sharing passwords for convenience',
        'Regular awareness training plus verification procedures',
        'D',
        'People are the target, so trained, skeptical staff backed by out-of-band verification policies are the best defense.',
    ),
]

THREAT_MODELING_EXTRA = [
    (
        'In STRIDE, which letter maps to Information Disclosure?',
        'The I',
        'The R',
        'The D',
        'The S',
        'A',
        'STRIDE stands for Spoofing, Tampering, Repudiation, Information disclosure, Denial of service, and Elevation of privilege.',
    ),
    (
        'A data-flow diagram (DFD) is used in threat modeling to:',
        'Track project budgets',
        'Map how data moves and where trust boundaries lie',
        'Schedule releases',
        'Store passwords',
        'B',
        'DFDs visualize processes, data stores, and flows so you can spot where untrusted data crosses trust boundaries.',
    ),
    (
        "Which STRIDE category does an attacker forging another user's identity fall under?",
        'Tampering',
        'Repudiation',
        'Spoofing',
        'Denial of service',
        'C',
        'Pretending to be someone or something else is Spoofing, which attacks the authentication property.',
    ),
    (
        'The PASTA methodology is:',
        'A password generator',
        'An encryption cipher',
        'A firewall rule set',
        'A risk-centric, attacker-focused threat-modeling process',
        'D',
        'PASTA (Process for Attack Simulation and Threat Analysis) is a seven-stage, risk-centric approach to threat modeling.',
    ),
    (
        'A DREAD score helps teams primarily to:',
        'Prioritize which threats to address first',
        'Generate keys',
        'Encrypt logs',
        'Detect malware',
        'A',
        "By scoring each threat's risk dimensions, DREAD produces a ranking that guides where to spend limited mitigation effort.",
    ),
    (
        'Which is an example of a mitigation for a Spoofing threat?',
        'Bigger disks',
        'Stronger authentication / MFA',
        'Faster CPUs',
        'More logging only',
        'B',
        'Spoofing is countered by robust authentication mechanisms that make identity harder to forge.',
    ),
    (
        'Attack trees are useful because they:',
        'Replace all testing',
        'Encrypt the network',
        'Break a goal into the steps an attacker could take',
        'Generate passwords',
        'C',
        "Attack trees decompose an attacker's objective into sub-goals and methods, revealing paths to defend.",
    ),
    (
        'The main purpose of identifying trust boundaries is to:',
        'Speed up the app',
        'Reduce code size',
        'Improve UI design',
        'Focus validation and controls where privilege changes',
        'D',
        'Data crossing from lower to higher trust is where most threats arise, so controls should concentrate there.',
    ),
    (
        'Residual risk is:',
        'Risk remaining after mitigations are applied',
        'Risk before any controls',
        'Risk that cannot exist',
        'Risk from backups',
        'A',
        'No control is perfect; residual risk is what remains and must be formally accepted, transferred, or further reduced.',
    ),
    (
        'Which property does a digital signature most directly support against repudiation?',
        'Availability',
        'Non-repudiation',
        'Confidentiality',
        'Latency',
        'B',
        'Signatures provide cryptographic proof of origin, so a party cannot credibly deny having performed an action.',
    ),
    (
        'When threat modeling, an asset is best described as:',
        'Any office furniture',
        'A type of firewall',
        'Something of value worth protecting (data, function)',
        'A coding style',
        'C',
        'Assets are what attackers want and you must protect, such as sensitive data, credentials, or critical functionality.',
    ),
    (
        'Elevation of Privilege is mitigated mainly by:',
        'Ignoring permissions',
        'Adding more RAM',
        'Using shorter URLs',
        'Enforcing authorization and least privilege',
        'D',
        'Strict, server-side authorization checks and minimal granted rights prevent users from gaining capabilities they should not have.',
    ),
    (
        'A threat-modeling output that developers can act on is:',
        'A prioritized list of threats with mitigations and owners',
        'A marketing plan',
        'A pricing sheet',
        'A network diagram only',
        'A',
        'Effective threat modeling produces actionable, tracked mitigations assigned to owners, not just a list of fears.',
    ),
    (
        "Microsoft's threat-modeling card game and tool are commonly associated with:",
        'DREAD only',
        'The STRIDE methodology',
        'Penetration testing',
        'Password cracking',
        'B',
        "Microsoft built tooling and the 'Elevation of Privilege' card game around STRIDE to make threat modeling approachable.",
    ),
    (
        "Why model threats from an attacker's perspective?",
        'It is faster to code',
        'It avoids documentation',
        'It reveals realistic attack paths and motivations',
        'It removes the need for testing',
        'C',
        'Thinking like an attacker helps you anticipate how real adversaries would abuse the system, leading to better defenses.',
    ),
    (
        'A countermeasure for a Tampering threat to data in transit is:',
        'Plaintext HTTP',
        'Disabling logs',
        'Larger packets',
        'TLS with integrity checks',
        'D',
        'TLS protects data in transit with both encryption and integrity verification, detecting unauthorized modification.',
    ),
    (
        'Threat modeling should be repeated when:',
        'The design, features, or trust boundaries change',
        'Never after launch',
        'Only every five years',
        'Only the logo changes',
        'A',
        'New features and architectural changes can introduce new attack surface, so the model must be revisited.',
    ),
    (
        'Which question best frames the start of a threat-modeling session?',
        'What font should we use?',
        'What are we building and what can go wrong?',
        'What is our marketing budget?',
        'Who designed the logo?',
        'B',
        'Foundational threat-modeling questions include what you are building, what can go wrong, what you will do about it, and did you do a good job.',
    ),
    (
        'LINDDUN is a methodology focused specifically on:',
        'Performance tuning',
        'UI accessibility',
        'Privacy threats',
        'Database indexing',
        'C',
        'LINDDUN extends threat modeling to privacy concerns such as linkability, identifiability, and disclosure of information.',
    ),
    (
        'Accepting a risk is appropriate when:',
        'It is always best',
        'The risk is critical',
        'There is unlimited budget',
        'The cost of mitigation outweighs the low impact/likelihood',
        'D',
        'Formal risk acceptance is reasonable for low-impact, low-likelihood threats where mitigation would cost more than the risk warrants.',
    ),
]

PASSWORD_ATTACKS_EXTRA = [
    (
        'A rainbow table attack is defeated primarily by:',
        'Adding a unique random salt to each password hash',
        'Using a longer username',
        'Disabling MFA',
        'Shortening passwords',
        'A',
        'Per-user salts make precomputed hash tables useless because identical passwords produce different hashes.',
    ),
    (
        'A dictionary attack tries passwords from:',
        'Random bytes only',
        'A list of common words and known passwords',
        'Hardware tokens',
        'Certificate stores',
        'B',
        'Dictionary attacks use curated wordlists of likely passwords, which is much faster than pure brute force against weak passwords.',
    ),
    (
        'Why is SMS-based MFA weaker than an authenticator app or hardware key?',
        'It is too fast',
        'It needs no phone',
        'SIM swapping and SMS interception can capture codes',
        'It uses encryption',
        'C',
        'Attackers can hijack a phone number via SIM swapping or intercept texts, so app-based TOTP or FIDO keys are stronger.',
    ),
    (
        'Passkeys (FIDO2/WebAuthn) resist phishing because they:',
        'Are shorter to type',
        'Reuse one secret everywhere',
        'Are sent by email',
        'Are cryptographically bound to the legitimate site origin',
        'D',
        'A passkey only authenticates to the exact origin it was registered with, so a fake site cannot trigger a valid response.',
    ),
    (
        'Credential stuffing tools succeed at scale by:',
        'Replaying breached username/password pairs across sites',
        'Guessing one account slowly',
        'Asking users politely',
        'Disabling the internet',
        'A',
        'Automated tools test leaked credential pairs against many services, exploiting password reuse.',
    ),
    (
        'The recommended modern guidance for password length is to favor:',
        'Frequent forced rotation',
        'Long passphrases without mandatory periodic changes',
        'Short complex strings',
        'Reusing one strong password',
        'B',
        'Current NIST guidance emphasizes length and screening against breached lists over arbitrary complexity and forced rotation.',
    ),
    (
        'A keylogger primarily threatens passwords by:',
        'Encrypting them',
        'Hashing them',
        'Capturing them as the user types',
        'Rotating them',
        'C',
        'Keyloggers record keystrokes, capturing credentials directly regardless of their strength.',
    ),
    (
        'Account lockout policies help against brute force but can enable:',
        'Stronger hashing',
        'Faster logins',
        'Better encryption',
        'Denial-of-service by locking many accounts',
        'D',
        'Aggressive lockouts can be abused to lock legitimate users out, so rate limiting and risk-based throttling are often preferred.',
    ),
    (
        'Storing password hashes with a slow algorithm like Argon2 is good because it:',
        'Makes large-scale offline cracking expensive',
        'Speeds up cracking',
        'Removes the need for salts',
        'Encrypts the database',
        'A',
        'Deliberately slow, memory-hard hashing dramatically raises the cost of brute-forcing stolen hashes.',
    ),
    (
        'Single sign-on (SSO) improves security mainly by:',
        'Removing all passwords forever',
        'Reducing the number of credentials users must manage',
        'Sharing one password publicly',
        'Disabling MFA',
        'B',
        'Fewer credentials, centrally protected and MFA-enforced, reduce reuse and phishing surface compared to many separate logins.',
    ),
    (
        'Pass-the-hash attacks exploit:',
        'Plaintext passwords only',
        'Hardware tokens',
        'Reusing a captured password hash to authenticate',
        'Salting',
        'C',
        'If a system accepts the hash itself for authentication, an attacker who steals it can log in without knowing the plaintext password.',
    ),
    (
        "A password manager's master password should be:",
        'Short and reused',
        'Written on a sticky note',
        'The same as your email',
        'A long, unique passphrase protected by MFA',
        'D',
        'The master password protects every stored secret, so it must be strong, unique, and ideally backed by MFA.',
    ),
    (
        'Which signal best indicates a credential-stuffing campaign in logs?',
        'A spike in failed logins across many accounts from few IPs',
        'Steady normal logins',
        'Fewer requests than usual',
        'Only successful logins',
        'A',
        'Mass failed attempts spread across many accounts is a hallmark of automated credential stuffing or spraying.',
    ),
    (
        'Conditional access / risk-based authentication adds security by:',
        'Always allowing logins',
        'Requiring extra verification for anomalous sign-ins',
        'Disabling passwords',
        'Caching credentials',
        'B',
        'Evaluating signals like location, device, and behavior lets the system step up authentication only when risk is elevated.',
    ),
    (
        'Why should default and vendor-supplied passwords be changed immediately?',
        'They expire too slowly',
        'They are too long',
        'They are publicly known and widely attacked',
        'They disable MFA',
        'C',
        'Default credentials are documented online and among the first things attackers and automated bots try.',
    ),
    (
        'A brute-force attack against a hashed password offline is slowed most by:',
        'A faster network',
        'A shorter salt',
        'Disabling logging',
        'A strong, slow hashing function and high entropy password',
        'D',
        'High password entropy combined with a deliberately slow hash makes the search space and per-guess cost both impractical.',
    ),
    (
        'Token theft (session hijacking) can bypass MFA because:',
        'A stolen valid session token needs no re-authentication',
        'It guesses the password',
        'It cracks the hash',
        'It disables the server',
        'A',
        'If an attacker steals a live session cookie or token, they ride the existing authenticated session without re-passing MFA.',
    ),
    (
        'A good practice when a data breach exposes your password is to:',
        'Reuse it elsewhere',
        'Change it everywhere it was reused and enable MFA',
        'Ignore it',
        'Make it shorter',
        'B',
        'Breached passwords should be retired immediately, especially anywhere reused, and accounts hardened with MFA.',
    ),
    (
        'Hardware security keys protect logins by:',
        'Displaying the password',
        'Emailing a code',
        'Performing origin-bound cryptographic challenge-response',
        'Storing passwords in plaintext',
        'C',
        'A hardware key signs a challenge tied to the real site, providing strong, phishing-resistant authentication.',
    ),
    (
        'Enforcing a breached-password screening at sign-up:',
        'Slows the database',
        'Disables MFA',
        'Encrypts the network',
        'Blocks users from choosing known-compromised passwords',
        'D',
        'Checking new passwords against breach corpora stops users from picking passwords already known to attackers.',
    ),
]

MALWARE_EXTRA = [
    (
        'A computer worm differs from a virus because it:',
        'Self-propagates across networks without user action',
        'Needs a host file to spread',
        'Cannot replicate',
        'Only runs offline',
        'A',
        'Worms spread autonomously over networks, while viruses attach to a host file and need the user to run it.',
    ),
    (
        'A rootkit is especially dangerous because it:',
        'Speeds up the OS',
        'Hides its presence deep in the system',
        'Only logs keystrokes',
        'Cannot persist',
        'B',
        'Rootkits embed at low levels (kernel or firmware) to conceal malware and evade detection and removal.',
    ),
    (
        'Fileless malware is hard to detect because it:',
        'Writes large files to disk',
        'Always shows a pop-up',
        'Runs in memory using legitimate system tools',
        'Requires admin install',
        'C',
        'Fileless attacks live in memory and abuse trusted tools like PowerShell, leaving little for signature-based scanners to find.',
    ),
    (
        'The 3-2-1 backup rule recommends:',
        '3 passwords, 2 keys, 1 PIN',
        '3 servers, 2 admins, 1 backup',
        '3 scans daily',
        '3 copies, 2 media types, 1 offsite/offline',
        'D',
        'Keeping three copies on two media types with one offsite/offline copy ensures you can recover even from ransomware or disaster.',
    ),
    (
        'Double-extortion ransomware adds pressure by:',
        'Stealing data and threatening to leak it as well as encrypting',
        'Speeding up the PC',
        'Backing up files',
        'Improving security',
        'A',
        'Attackers exfiltrate data before encrypting, then threaten public release so victims pay even if they have backups.',
    ),
    (
        'A logic bomb is malware that:',
        'Runs immediately on download',
        'Triggers when a specific condition or time is met',
        'Cannot be hidden',
        'Only affects printers',
        'B',
        'Logic bombs lie dormant until a trigger (a date, event, or condition) fires the malicious payload.',
    ),
    (
        'Macro malware commonly spreads through:',
        'Plain text files',
        'Image thumbnails',
        'Office documents with malicious embedded macros',
        'Disabled scripts',
        'C',
        'Attackers trick users into enabling macros in Word/Excel files, which then download or run the malware.',
    ),
    (
        'A botnet is:',
        'A backup network',
        'A firewall cluster',
        'An antivirus tool',
        'A network of compromised devices controlled by an attacker',
        'D',
        'Botnets are armies of infected machines that attackers command remotely for spam, DDoS, or further attacks.',
    ),
    (
        'Which is the safest reaction to a ransomware demand?',
        'Isolate, report to IT/authorities, and restore from backups',
        'Pay immediately',
        'Reboot repeatedly',
        'Open the readme repeatedly',
        'A',
        'Paying funds crime and offers no guarantee; isolating and restoring from clean backups is the recommended response.',
    ),
    (
        'Adware is best described as malware that:',
        'Encrypts files',
        'Forces unwanted advertisements and may track the user',
        'Improves browsing',
        'Backs up data',
        'B',
        'Adware bombards users with ads and often bundles tracking, degrading performance and privacy.',
    ),
    (
        'EDR (Endpoint Detection and Response) helps against malware by:',
        'Only blocking ads',
        'Encrypting email',
        'Monitoring endpoint behavior to detect and respond to threats',
        'Replacing backups',
        'C',
        'EDR continuously watches process and system behavior, enabling detection of novel or fileless attacks and rapid response.',
    ),
    (
        'Application allowlisting reduces malware risk by:',
        'Allowing any program',
        'Disabling antivirus',
        'Opening all ports',
        'Permitting only approved executables to run',
        'D',
        'If only known-good applications can execute, unknown malware is blocked from running in the first place.',
    ),
    (
        'A common ransomware initial-access vector is:',
        'Phishing emails and exposed RDP/remote services',
        'Reading a printed memo',
        'Powering off the PC',
        'Using a password manager',
        'A',
        'Most ransomware enters through phishing or weakly protected remote-access services like RDP.',
    ),
    (
        'Spyware most directly threatens:',
        'Availability only',
        'Confidentiality by stealing data and activity',
        'Backup speed',
        'Disk size',
        'B',
        'Spyware covertly collects information such as credentials, browsing, and keystrokes, breaching confidentiality.',
    ),
    (
        'Why are regular, tested restores important, not just backups?',
        'Restores look nice',
        'It speeds the CPU',
        'Backups are worthless if they cannot actually be restored',
        'It encrypts files',
        'C',
        'Untested backups often fail when needed; periodic restore drills confirm you can truly recover.',
    ),
    (
        'Patching systems promptly reduces malware risk because it:',
        'Adds new features',
        'Increases attack surface',
        'Disables backups',
        'Closes vulnerabilities that malware exploits to spread',
        'D',
        'Many worms and ransomware spread via known, unpatched vulnerabilities, so timely patching removes those entry points.',
    ),
    (
        'Network segmentation limits ransomware impact by:',
        'Containing infections so they cannot reach the whole network',
        'Speeding up files',
        'Disabling logging',
        'Sharing all drives',
        'A',
        'Dividing the network into isolated zones stops malware from freely spreading laterally to every system.',
    ),
    (
        'Sandbox analysis of a suspicious attachment lets defenders:',
        'Run it on production',
        'Detonate it safely to observe its behavior',
        'Email it to users',
        'Disable antivirus',
        'B',
        'A sandbox executes the sample in an isolated environment so analysts can study its actions without risking real systems.',
    ),
    (
        'Polymorphic malware evades signature detection by:',
        'Staying identical',
        'Deleting itself',
        'Changing its code/appearance on each infection',
        'Using one fixed hash',
        'C',
        'Polymorphic code mutates while keeping its function, so static signatures of a single variant fail to catch it.',
    ),
    (
        "A trojan dropper's main job is to:",
        'Back up files',
        'Encrypt backups',
        'Patch the OS',
        'Install additional malware onto the victim system',
        'D',
        'Droppers are first-stage payloads whose purpose is to fetch and install further malicious components.',
    ),
]

NETWORK_WEB_EXTRA = [
    (
        'ARP spoofing on a local network enables an attacker to:',
        'Intercept traffic by associating their MAC with another IP',
        'Speed up Wi-Fi',
        'Encrypt the LAN',
        'Block all malware',
        'A',
        "By forging ARP replies, an attacker reroutes a victim's traffic through their machine, enabling man-in-the-middle attacks.",
    ),
    (
        'A SYN flood is a type of:',
        'Phishing',
        'Denial-of-service attack exhausting connection resources',
        'Encryption scheme',
        'Backup method',
        'B',
        "SYN floods send many half-open TCP connections to exhaust the server's connection table, denying service to real users.",
    ),
    (
        'Stored (persistent) XSS is more dangerous than reflected XSS because the payload:',
        'Disappears immediately',
        'Only affects the attacker',
        'Is saved and served to many future visitors',
        'Needs no browser',
        'C',
        'Persistent XSS lives on the server and executes for every user who views the affected content, amplifying its reach.',
    ),
    (
        'DNS spoofing/cache poisoning causes victims to:',
        'Reach the right site faster',
        'Encrypt their DNS',
        'Block all ads',
        'Be directed to attacker-controlled addresses',
        'D',
        'Corrupting DNS responses sends users to malicious servers even when they type a legitimate domain.',
    ),
    (
        'Mutual TLS (mTLS) strengthens security by:',
        'Authenticating both client and server with certificates',
        'Only encrypting one way',
        'Disabling certificates',
        'Using plaintext',
        'A',
        'mTLS verifies the identities of both endpoints, preventing unauthorized clients and reducing impersonation.',
    ),
    (
        'HTTP Strict Transport Security (HSTS) helps by:',
        'Allowing HTTP downgrades',
        'Forcing browsers to use HTTPS for the site',
        'Disabling TLS',
        'Caching passwords',
        'B',
        'HSTS instructs browsers to connect only over HTTPS, thwarting SSL-stripping downgrade attacks.',
    ),
    (
        'Broken access control (e.g., missing role checks) is dangerous because it:',
        'Slows the page',
        'Improves caching',
        'Lets users perform actions or view data beyond their rights',
        'Encrypts traffic',
        'C',
        'Without proper server-side authorization, users can reach functions or records they should never access.',
    ),
    (
        'A reflected XSS payload is typically delivered via:',
        'A stored database record',
        'A printed document',
        'A firewall rule',
        'A crafted link/parameter the victim clicks',
        'D',
        'Reflected XSS bounces the injected script off the server in the response to a request the victim was tricked into making.',
    ),
    (
        'An amplification DDoS (e.g., DNS/NTP) works by:',
        'Eliciting large responses to a spoofed victim address',
        'Sending tiny replies',
        'Encrypting traffic',
        'Blocking spoofing',
        'A',
        'Attackers send small spoofed requests to services that return much larger responses aimed at the victim, multiplying the flood.',
    ),
    (
        'A Web Application Firewall (WAF) primarily helps by:',
        'Replacing all code fixes',
        'Filtering and blocking malicious HTTP requests',
        'Storing backups',
        'Encrypting disks',
        'B',
        'A WAF inspects web traffic and blocks common attack patterns, buying time but not replacing secure coding.',
    ),
    (
        'SSL stripping downgrades a connection by:',
        'Upgrading to HTTPS',
        'Adding a certificate',
        'Tricking the victim into using unencrypted HTTP',
        'Blocking the attacker',
        'C',
        'The attacker sits in the middle and serves HTTP to the victim while talking HTTPS to the server, exposing the traffic.',
    ),
    (
        'CSRF is effective when an application relies solely on:',
        'Anti-CSRF tokens',
        'SameSite cookies',
        'Re-authentication',
        'Ambiently sent cookies to authorize state changes',
        'D',
        "If a request is trusted just because the browser auto-sends the session cookie, an attacker's page can forge it; tokens/SameSite fix this.",
    ),
    (
        'A VPN protects data on untrusted Wi-Fi mainly by:',
        'Encrypting traffic in a tunnel to a trusted endpoint',
        'Speeding up DNS',
        'Blocking all ads',
        'Disabling TLS',
        'A',
        'A VPN wraps your traffic in an encrypted tunnel so local eavesdroppers on the network cannot read it.',
    ),
    (
        'Server-Side Request Forgery (SSRF) typically lets attackers:',
        'Speed up requests',
        'Make the server reach internal systems it should not expose',
        'Encrypt the database',
        'Improve caching',
        'B',
        "SSRF abuses a server's ability to fetch URLs to pivot into internal services and cloud metadata endpoints.",
    ),
    (
        'Rate limiting an API helps defend against:',
        'Better encryption',
        'Stronger TLS',
        'Brute force, scraping, and certain DoS abuse',
        'Larger payloads',
        'C',
        'Capping request rates blunts automated abuse such as credential brute forcing and resource-exhausting floods.',
    ),
    (
        'Certificate pinning helps mobile apps resist:',
        'Faster loading',
        'Battery drain',
        'Larger downloads',
        'Man-in-the-middle attacks using rogue certificates',
        'D',
        "Pinning ties the app to expected certificates/keys, so an attacker's fraudulent certificate is rejected.",
    ),
    (
        'An open redirect vulnerability can be abused to:',
        "Lend a trusted domain's credibility to a phishing link",
        'Speed up navigation',
        'Encrypt the URL',
        'Block cookies',
        'A',
        'Open redirects let attackers craft links on a trusted site that forward victims to malicious destinations.',
    ),
    (
        'Which is the correct fix for IDOR beyond using random IDs?',
        'Hide the endpoint',
        'Enforce per-request server-side ownership/authorization checks',
        'Cache responses',
        'Compress the response',
        'B',
        'The server must verify the authenticated user is allowed to access the specific object on every request.',
    ),
    (
        'Session fixation is mitigated by:',
        'Reusing the session ID',
        'Disabling cookies',
        'Regenerating the session ID after login',
        'Logging passwords',
        'C',
        'Issuing a fresh session identifier upon authentication prevents an attacker from fixing a known session ID before login.',
    ),
    (
        'Setting cookies with HttpOnly and Secure flags helps by:',
        'Speeding requests',
        'Disabling TLS',
        'Allowing any origin',
        'Blocking script access and requiring HTTPS for the cookie',
        'D',
        'HttpOnly stops JavaScript (and thus XSS) from reading the cookie, while Secure ensures it is only sent over encrypted connections.',
    ),
]

EXTRA_QUESTIONS = {
    "Secure Coding Practices": SECURE_CODING_EXTRA,
    "Social Engineering Awareness": SOCIAL_ENGINEERING_EXTRA,
    "Threat Modeling": THREAT_MODELING_EXTRA,
    "Password & Authentication Attacks": PASSWORD_ATTACKS_EXTRA,
    "Malware & Ransomware": MALWARE_EXTRA,
    "Network & Web Attacks": NETWORK_WEB_EXTRA,
}
